config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'contact', to: 'pages#contact'

  resources :articles

  get 'signup' , to: 'users#new'

  resources :users, except: [:new]

  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  delete 'logout' , to: 'sessions#destroy'

  resources :categories , except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: {minimum:10, maximum:100}
  validates :description, presence: true, length: {minimum:10, maximum:1000}

  paginates_per 10

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories


  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name

  paginates_per 10

end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}

  has_many :articles , dependent: :destroy
  validates :username, presence: true,
  uniqueness: {case_sensitive: false},
  length: {minimum: 3, maximum:25}

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true,
                    uniqueness: {case_sensitive: false}, # nothing just moved to new line for better view,
                    format: {with: VALID_EMAIL_REGEX},
                    length: {maximum:105}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user , :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform this action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController<ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user , except: [:show, :index]
  before_action :require_current_user , only: [:edit, :update , :destroy]

  def show
  end

  def index
    @articles = Article.order(:created_at).page params[:page]
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article created successfully..."
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article updated successfully..."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
    flash[:notice] = "Article deleted successfully..."
  end


  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids:[])
  end

  def require_current_user
    if @article.user != current_user && !current_user.admin?
      redirect_to @article
      flash[:notice] = "You can't perform this action"
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin_user, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))
    if @category.save
      flash[:notice] = "New category added"
      redirect_to @category
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(set_params)
      flash[:notice] = "Article updated successfully..."
      redirect_to @category
    else
      render 'edit'
    end
  end

  def show
    @articles = @category.articles
  end

  def index
    @categories = Category.order(:name).page params[:page]
  end

  def destroy
    @category.destroy
    redirect_to categories_path
    flash[:notice] = "Catgory deleted successfully..."
  end

  private

  def set_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def require_admin_user
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins allowed"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def contact
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to articles_path if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "Please check your email and password again"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user , only: [:edit , :update]
  before_action :require_current_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.order(:title).page params[:page]
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
    redirect_to articles_path if logged_in?
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username} to Alpha Blog"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Updated your profile successfully"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Deleted account successfully..."
    redirect_to root_path
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_current_user
    if @user != current_user && !current_user.admin?
      redirect_to @user
      flash[:notice] = "You don't have access to this account"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for ( user, options = { size: 80 } )
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?=#{size}"
    image_tag(gravatar_url , alt: user.username )
  end




end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="row row-cols-3 row-cols-md-4 g-4">
  <% @articles.each do |a| %>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= a.title %></h5>
          <p class="card-text"><%= a.description %></p>
          <p class="card-text">Author: <%= a.user.username if a.user %></p>
          <%= link_to 'Show', article_path(a), class: "btn btn-primary" %>
          <% if logged_in? && (a.user == current_user || current_user.admin? ) %>
            <%= link_to 'Edit', edit_article_path(a), class: "btn btn-warning" %>
            <%= link_to "Delete", article_path(a), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" %>
          <% end %> <br> <br>
          <small class="card-text">Created: <%= time_ago_in_words(a.created_at) %> ago ; Edited: <%= time_ago_in_words(a.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_with model: @article, data: {turbo: false} do |f| %>
    <div class="col-3">
        <%= f.label :title, class:"form-label" %> <br>
    </div>
    <div class="col-3">
        <%= f.text_field :title, class:"form-control" %> <br> <br>
    </div>
    <div class="col-3">
        <%= f.label :description, class:"form-label" %> <br>
    </div>
    <div class="col-3">
        <%= f.text_area :description, class:"form-control" %> <br> <br>
    </div>
    <div class="col-3">
        <%= f.label :category, class:"form-label" %> <br>
    </div>
    <div class="col-3 ">
        <%= f.collection_select :category_ids, Category.all, :id, :name , {prompt: "Select category (optional)"} , {class: 'form-select', multiple: true} %> <br> <br>
    </div>
    <div class="col-3">
        <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles index</h1>

<%= link_to 'Create article', new_article_path, class: "btn btn-primary" %>
<br>
<br>

<%= paginate @articles %>
<%= render 'article' %>

app/views/articles/new.html.erb
<h1>Create new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<h3><strong>Description: </strong><%= @article.description %></h3>
<p><strong>Author: </strong><%= @article.user.username if @article.user %></p>
<% if @article.categories.any? %>
  Categories: <% @article.categories.each do |category|%>
    <span class="badge rounded-pill text-bg-primary"><%= link_to category.name, category_path(category) , style: "text-decoration: none" , class: "link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover" %></span>
  <% end %>
<% end %>
<br>
<br>
<%= link_to 'Go to homepage', articles_path %>

<br>
<br>
<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
  <%= link_to 'Edit', edit_article_path, class: "btn btn-warning" %>
  <%= link_to "Delete", @article, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" %>
<% end %>

app/views/categories/_category.html.erb
<div class="row row-cols-3 row-cols-md-4 g-4">
  <% @categories.each do |a| %>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= a.name %></h5>
          <%= link_to 'Show', category_path(a), class: "btn btn-primary" %>
          <% if logged_in? && current_user.admin? %>
            <%= link_to 'Edit', edit_category_path(a), class: "btn btn-warning" %>
            <%# <%= link_to "Delete", category_path(a), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_with model: @category, data: {turbo: false} do |f| %>
    <div class="col-3">
        <%= f.label :name, class:"form-label" %> <br>
    </div>
    <div class="col-3">
        <%= f.text_field :name, class:"form-control" %> <br> <br>
    </div>
    <div class="col-3">
        <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing: <%= @category.name %></h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Category index</h1>

<% if logged_in? && current_user.admin? %>
  <%= link_to 'Create category', new_category_path, class: "btn btn-primary" %>
<% end %>
<br>
<br>

<%= paginate @categories %>
<%= render 'category' %>

app/views/categories/new.html.erb
<h1>Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<%# <%= link_to 'Delete category', @category , data: {turbo_method: :delete , turbo_confirm: "Are you sure?" } %>
<%= render 'articles/article' %>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg sticky-top bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Alpha Blog', root_path , class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Bloggers', users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Categories', categories_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Articles', articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', contact_path, class: "nav-link" %>
        </li>
      </ul>
      <% if logged_in? %>
        <%= link_to 'Log out', logout_path, data: {turbo_method: :delete}, class: "btn btn-outline-success" %>
      <% else %>
        <%= link_to 'Log in', login_path, class: "btn btn-outline-success" %>
      <% end %>

      <% if logged_in? %>
        <%= link_to current_user.username , user_path(current_user), class: "btn btn-warning" %>
      <% else %>
        <%= link_to 'Sign up', signup_path, class: "btn btn-warning" %>
      <% end %>

    </div>
  </div>
  <% if logged_in? %>
    <div class="dropdown">
      <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Profile [<%= current_user.username %>] <%= " - Admin" if current_user.admin? %>
      </a>
      <ul class="dropdown-menu" style="ul > a{margin:10px 0px}">
        <%= link_to 'View profile', user_path(current_user), class: "btn btn-warning", style: "margin: 10px 5px" %>
        <%= link_to 'Edit profile', edit_user_path(current_user), class: "btn btn-warning", style: "margin: 10px 5px" %>
        <% if current_user.admin? %>
          <%= link_to 'View categories', categories_path, class: "btn btn-warning", style: "margin: 10px 5px" %>
          <%= link_to 'Create new category', new_category_path, class: "btn btn-warning", style: "margin: 10px 5px" %>
        <% end %>
      </ul>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" %>
    <%= javascript_importmap_tags %>
    <style>
      body{
        overflow-x: hidden;
      }
      main{
        margin: 20px;
      }
      a{
        margin: 0 10px;
      }
    </style>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <main>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Contact us</h1>

app/views/pages/home.html.erb
<h1>Home</h1>
<%= link_to "Sign up", signup_path, class: "btn btn-success" %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">There are some errors</h3>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_with model: @user, data: {turbo: false} do |f| %>
    <div class="col-3">
        <%= f.label :username, class:"form-label" %> <br>
    </div>
    <div class="col-3">
        <%= f.text_field :username, class:"form-control" %> <br> <br>
    </div>
    <div class="col-3">
        <%= f.label :email, class:"form-label" %> <br>
    </div>
    <div class="col-3">
        <%= f.email_field :email, class:"form-control" %> <br> <br>
    </div>
    <div class="col-3">
        <%= f.label :password, class:"form-label" %> <br>
    </div>
    <div class="col-3">
        <%= f.password_field :password, class:"form-control" %> <br> <br>
    </div>
    <div class="col-3">
        <%= f.submit ( @user.new_record? ? "Sign up" : "Update account") , class: "btn btn-primary" %>
    </div>
<% end %>

app/views/users/_user.html.erb
<div class="row row-cols-3 row-cols-md-4 g-4">
  <% @users.each do |user| %>
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= user.username %></h5>
          <p class="card-text"><%= user.email %></p>
          <p class="card-text"><%= pluralize(user.articles.count, "article" ) %></p>
          <p class="card-text">Joined <%= time_ago_in_words(user.created_at) %> ago</p>
          <%= link_to 'View profile', user_path(user), class: "btn btn-primary" %>
          <% if logged_in? %>
            <% if user == current_user %>
              <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-warning" %>
            <% end %>
            <% if current_user.admin? %>
              <%= link_to 'Delete profile', user_path(user), data:{turbo_method: :delete , turbo_confirm: "Are you sure you want to delete the user #{user.username} all #{user.articles.count} articles associated to this account?"},class: "btn btn-warning" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h3>Edit user <%=@user.username%></h3>

<%= render 'form' %>

app/views/users/index.html.erb
<%= render 'user' %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h2><%= @user.username %>'s Profile</h2> <br>
<%= gravatar_for @user , size: 200 %> <br>
<%= @user.email %> <br> <br>
<% if logged_in? && @user == current_user %>
  <%= link_to 'Edit profile', edit_user_path(@user), class: "btn btn-warning" %>
  <%= link_to 'Delete profile', @user, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},class: "btn btn-danger" %>
<% end %>
<%= paginate @articles %>
<%= render 'articles/article' %>